name: Extract package version create information
description: Extracts JSON data from the sfdx force:package:version:create command
author: muenzpraeger
inputs:
    json:
        description: JSON output of package version create command
        required: true
outputs:
    errorMessages:
        description: Error messages of package version create command
    isSuccess:
        description: Response status of package version create command
    packageVersionId:
        description: ID of created package version

runs:
    using: 'node12'
    main: 'index.js'
